void displayMenu();
void handleCommands(int num);
void handleHornCommands();
void handleHeadlightsCommands();
void handleTurnSignalsCommands();
void handleWindshieldWipersCommands();
void handleHazardLightsCommands();
void handleCruiseControlCommands();
void handleRadioVolumeCommands();
void handleRadioTuningCommands();
void initializeFeatureHandlers();
void cleanupFeatureHandlers();