// menu.h
#ifndef MENU_H
#define MENU_H

void hornMenu();
void headlightsMenu();
void turnSignalsMenu();
void sunroofMenu();
void trunkReleaseMenu();
void fuelCapReleaseMenu();
void driveModeMenu();
void tractionMenu();
void steeringMenu();
void interiorLightMenu();
void parkingBrakeMenu();
void heatedSeatMenu();
void cooledSeatMenu();
void autoHoldMenu();
void radioSourceMenu();
void climateAirflowMenu();
void climateFanMenu();
void ClimateTempMenu();
void DefrostMenu();
void WindowLockMenu();
void DoorLockMenu();
void mirrorAdjustMenu();
void powerwindowMenu();
void seatAdjustMenu();
#endif // MENU_H