// menu.h
#ifndef MENU_H
#define MENU_H

void hornMenu();
void headlightsMenu();
void turnSignalsMenu();
void sunroofMenu();
void trunkReleaseMenu();
void fuelCapReleaseMenu();
void driveModeMenu();
void tractionMenu();
void steeringMenu();
void interiorLightMenu();
void parkingBrakeMenu();
void heatedSeatMenu();
void cooledSeatMenu();
void autoHoldMenu();
void radioSourceMenu();
void climateAirflowMenu();
void climateFanMenu();
void ClimateTempMenu();
void DefrostMenu();
void WindowLockMenu();
void DoorLockMenu();
void mirrorAdjustMenu();
void powerwindowMenu();
void seatAdjustMenu();
void fogLightsMenu();
void seatHeaterMenu();
void trailerControlMenu();
void seatCoolerMenu();
void handsFreeMenu();
void hudAdjustMenu();
void gloveBoxReleaseMenu();
void emergencyBrakeMenu();

void MUTE_BUTTON_MENU();
void VOICE_COMMAND_MENU();
void PARKING_ASSIST_MENU();
void REAR_DEFROST_MENU();
void CHILD_LOCK_MENU();
void NAVIGATION_MENU();
void LANE_ASSIST_MENU();
void PARKING_ASSIST_MENU();
void HILL_DESCENT_MENU();
void Phone_End_Call_MENU();
void Phone_Answer_MENU();

#endif // MENU_H